Go integration tests
oxidrive/oxidrive pull request #26
Opened 2024-04-16 21:46 UTC by fedeizzo

What does this PR do?
---
- Update Go test tooling system.
- Add function to tag integration tests.

Motivation
---
A developer has to have the ability of tagging some tests as `integration` and run them optionally, because they may depend on external dependencies that have to be run separtely.

Testing
---
```sh
$ just server/test
github.com/oxidrive/oxidrive/server/internal/infrastructure/file:
 ✓ File upload mock (0.00s)
 ✓ File upload mock with an error (0.00s)
 ✓ File upload mock without an error (0.00s)
 ∅ File upload postgres (0.00s)

=== Skipped
=== SKIP: server/internal/infrastructure/file TestFileUploadPostgres (0.00s)
    file_postgres_test.go:11: skipping integration tests, call go test with INTEGRATION_TEST set
```

```sh
$ just server/test-integration
github.com/oxidrive/oxidrive/server/internal/infrastructure/file:
 ✓ File upload mock (0.00s)
 ✓ File upload mock with an error (0.00s)
 ✓ File upload mock without an error (0.00s)
 ✖ File upload postgres (0.00s)

=== Failed
=== FAIL: server/internal/infrastructure/file TestFileUploadPostgres (0.00s)
    file_postgres_test.go:13:
        	Error Trace:	<path>/file/file_postgres_test.go:13
        	Error:      	Not equal:
        	            	expected: 1
        	            	actual  : 2
        	Test:       	TestFileUploadPostgres

DONE 6 tests, 1 failure in 0.880s
error: Recipe `test-integration` failed on line 13 with exit code 1
```

2024-04-17 08:29 UTC, MatteoJoliveau commented
YES, THANK YOU

Out of curiosity: can we use build tags for this or am I misunderstanding how they work?

2024-04-17 13:01 UTC, fedeizzo commented
> YES, THANK YOU
> 
> Out of curiosity: can we use build tags for this or am I misunderstanding how they work?

Build tags are defined per file, this approach gives more control and allows us to tag only specific functions.

2024-04-17 13:19 UTC, MatteoJoliveau requested changes
Actually, we need to update the GHA workflows to set the envar to true, otherwise integration tests will never run.

2024-04-18 12:15 UTC, MatteoJoliveau submitted a review, later dismissed

2024-04-18 13:20 UTC, MatteoJoliveau submitted a review, later dismissed

2024-04-18 19:21 UTC, MatteoJoliveau approved these changes

2024-04-19 06:59 UTC, MatteoJoliveau approved these changes

2024-04-19 06:59 UTC, merged